server:
  port: 3110 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: loan-gateway # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
    gateway:
      discovery:
        locator:
          enabled: true # gateway可以发现nacos中的微服务，并自动生成转发路由

      routes:
        - id: loan-core
          uri: lb://loan-core
          predicates:
            - Path=/*/core/**
        - id: loan-sms
          uri: lb://loan-sms
          predicates:
            - Path=/*/sms/**
        - id: loan-oss
          uri: lb://loan-oss
          predicates:
            - Path=/*/oss/**